import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { Toaster } from "sonner";
import PublicNavbar from "@/components/shared/PublicNavbar";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
    >
      <body className="min-h-full flex flex-col container mx-auto px-4 sm:px-6 lg:px-8 bg-[#0f0d0b] text-white antialiased">
        <PublicNavbar/>
        {children}
        <Toaster
          position="top-center"
          closeButton
          toastOptions={{
            style: {
              background: "#0f172a",
              color: "#fff",
              borderRadius: "12px",
              border: "1px solid #334155",
              backdropFilter: "blur(20px)",
              WebkitBackdropFilter: "blur(20px)",
            },
          }}
        />
      </body>
    </html>
  );
}
